### ISSUE TITLE
JSDom ReferenceError: Element is not defined 

### ISSUE THREAD

**Issue by laggingreflex** [lukehorvat/computed-style-to-inline-style#1]
I'm trying to use this in node environment on a JSDom document. It gives the error:

```
ReferenceError: Element is not defined
```

It's because of this:

```
    if (!(element instanceof Element)) {
      throw new Error("Specified element is not an instance of Element.");
    }
```

Perhaps we can check with some [other methods](http://stackoverflow.com/questions/4754088/how-to-check-if-object-is-a-dom-element/4754104#4754104)? Like check for `element.tagName` or `nodeName`? 

edit: next error would be `getComputedStyle` which is also not available as a global var in node either. I guess I'm better off implementing it myself. 

BTW I was doing this for server-side-rendering, to inline all styles before serving the rendered html as text, and another thing I could really use was a "depth" that allowed inlining styles only up to a certain depth or element (for above-the-fold content, rest of the style kick in later with css anyways, and [because it seems `getComputedStyle` is expensive in JSDom](https://github.com/tmpvar/jsdom/issues/1560)). 

PS: Awesome lib, exactly what I was looking for!

**Comment by lukehorvat** [comment]
I've dropped the `instanceof` check in version 2. ✌️ `Window.getComputedStyle` throws an error if the object given to it isn't an `Element` anyway.
